#include "util.c"

#include <base/test.h>

SIMPLE(at_keyword, {
    RUN_SCANNER(FILE_AT_KEYWORD);
    SCANNER_ITERATOR();

    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_CC);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_CPP);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_SYS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_BUILTIN);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_HIDE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_HIDEOUT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AT_LEN);

    FREE_SCANNER();
});
