#include "util.c"

#include <base/test.h>

SIMPLE(keyword, {
    RUN_SCANNER(FILE_KEYWORD);
    SCANNER_ITERATOR();

    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ALIAS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AND);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ASM);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ASYNC);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_AWAIT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_BEGIN);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_BREAK);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_CAST);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_CATCH);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_CLASS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_COMPTIME);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_DEFER);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_DO);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_DROP);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ELIF);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ELSE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_END);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ENUM);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_ERROR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_FALSE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_FOR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_FUN);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_GET);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_GLOBAL);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_IF);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_IMPL);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_IMPORT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_IN);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_INCLUDE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_INHERIT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_IS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_LIB);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_MACRO);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_MATCH);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_MODULE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_MUT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_NEXT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_NIL);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_NONE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_NOT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_object);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_OBJECT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_OR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_PACKAGE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_PUB);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_RAISE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_RECORD);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_REF);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_REQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_RETURN);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_self);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_SELF);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_SET);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_TEST);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_TRACE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_TRAIT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_TRUE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_TRY);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_TYPE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_UNDEF);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_UNSAFE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_USE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_VAL);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_WHEN);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_WHILE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_KEYWORD_XOR);

    FREE_SCANNER();
});
