#include "util.c"

#include <base/test.h>

CASE(literal_suffix_int32, {
    RUN_SCANNER(FILE_LITERAL_SUFFIX_INT32);
    SCANNER_ITERATOR();

    TEST_ASSERT_EQ(CURRENT()->kind, LILY_TOKEN_KIND_LITERAL_SUFFIX_INT32);
    TEST_ASSERT_EQ(NEXT()->literal_suffix_int32, 32300);
    TEST_ASSERT_EQ(CURRENT()->kind, LILY_TOKEN_KIND_LITERAL_SUFFIX_INT32);
    TEST_ASSERT_EQ(NEXT()->literal_suffix_int32, 4095);
    TEST_ASSERT_EQ(CURRENT()->kind, LILY_TOKEN_KIND_LITERAL_SUFFIX_INT32);
    TEST_ASSERT_EQ(NEXT()->literal_suffix_int32, 14);
    TEST_ASSERT_EQ(CURRENT()->kind, LILY_TOKEN_KIND_LITERAL_SUFFIX_INT32);
    TEST_ASSERT_EQ(NEXT()->literal_suffix_int32, 19);

    FREE_SCANNER();
});
