#include "util.c"

#include <base/test.h>

SIMPLE(operator, {
    RUN_SCANNER(FILE_OPERATOR);
    SCANNER_ITERATOR();

    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_AMPERSAND_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_AMPERSAND);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_BANG);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_BAR_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_BAR_R_SHIFT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_BAR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_COLON_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_COLON_R_SHIFT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_DOT_DOT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_DOT_INTERROGATION);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_DOT_STAR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_EQ_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_HAT_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_HAT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_INTERROGATION);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_L_SHIFT_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_L_SHIFT_L_SHIFT_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_L_SHIFT_L_SHIFT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_L_SHIFT);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_MINUS_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_MINUS_MINUS_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_MINUS_MINUS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_MINUS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_NOT_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_PERCENTAGE_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_PERCENTAGE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_PLUS_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_PLUS_PLUS_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_PLUS_PLUS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_PLUS);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_SLASH_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_SLASH);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_STAR_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_STAR_STAR_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_STAR_STAR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_STAR);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_WAVE_EQ);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_WAVE);
    TEST_ASSERT_EQ(NEXT()->kind, LILY_TOKEN_KIND_XOR_EQ);

    FREE_SCANNER();
});
