/*
 * MIT License
 *
 * Copyright (c) 2022-2026 ArthurPV
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef LILY_CORE_CC_CI_DIAGNOSTIC_ERROR_H
#define LILY_CORE_CC_CI_DIAGNOSTIC_ERROR_H

#include <base/macros.h>

enum CIErrorKind
{
    CI_ERROR_KIND_UNCLOSED_COMMENT_BLOCK,
    CI_ERROR_KIND_UNCLOSED_COMMENT_DOC,
    CI_ERROR_KIND_MISMATCHED_CLOSING_DELIMITER,
    CI_ERROR_KIND_UNCLOSED_CHAR_LITERAL,
    CI_ERROR_KIND_INVALID_ESCAPE,
    CI_ERROR_KIND_UNCLOSED_STRING_LITERAL,
    CI_ERROR_KIND_REQUIRED_C89_OR_LATER,
    CI_ERROR_KIND_REQUIRED_C95_OR_LATER,
    CI_ERROR_KIND_REQUIRED_C99_OR_LATER,
    CI_ERROR_KIND_REQUIRED_C11_OR_LATER,
    CI_ERROR_KIND_REQUIRED_C17_OR_LATER,
    CI_ERROR_KIND_REQUIRED_C23_OR_LATER,
    CI_ERROR_KIND_PREPROCESSOR_ERROR,
    CI_ERROR_KIND_EXPECTED_TOKEN,
    CI_ERROR_KIND_ACCESS_TO_DROPPED_STRUCT_OR_UNION,
    CI_ERROR_KIND_ACCESS_TO_FREED_POINTER,
    CI_ERROR_KIND_ACCESS_TO_NULLABLE_POINTER,
    CI_ERROR_KIND_ACCESS_TO_UNDEFINED_VALUE,
    CI_ERROR_KIND_ALIGNOF_IN_PREPROCESSOR_CONDITION,
    CI_ERROR_KIND_BAD_INTEGER_LITERAL,
    CI_ERROR_KIND_BIT_NOT_ON_FLOAT,
    CI_ERROR_KIND_BREAK_OUTSIDE_OF_LOOP_OR_SWITCH,
    CI_ERROR_KIND_CALL_ON_NON_FUNCTION,
    CI_ERROR_KIND_CALL_TO_UNKNOWN_FUNCTION,
    CI_ERROR_KIND_CANNOT_ASSIGN_TO_ARRAY_DATA_TYPE,
    CI_ERROR_KIND_CANNOT_ASSIGN_TO_CONST_DATA_TYPE,
    CI_ERROR_KIND_CANNOT_COMBINE_STORAGE_CLASS_WITH_TYPEDEF,
    CI_ERROR_KIND_CANNOT_DEFINE_CI_VA_ARGS,
    CI_ERROR_KIND_CANNOT_INFER_INITIALIZER,
    CI_ERROR_KIND_CANNOT_INFER_ON_UNKNOWN_IDENTIFIER,
    CI_ERROR_KIND_CANNOT_INFER_PATH,
    CI_ERROR_KIND_CANNOT_REDEFINE_BUILTIN_FUNCTION,
    CI_ERROR_KIND_CANNOT_REDEFINE_PREDEFINED_MACRO,
    CI_ERROR_KIND_CANNOT_RESOLVE_CAST_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_CANNOT_RESOLVE_SIZE_OF_ANY_DATA_TYPE,
    CI_ERROR_KIND_CANNOT_RESOLVE_SIZE_OF_TYPE_INFO,
    CI_ERROR_KIND_CANNOT_USE_NON_COMPTIME_VALUE,
    CI_ERROR_KIND_CASE_OUTSIDE_OF_SWITCH,
    CI_ERROR_KIND_CI_YAML_NOT_FOUND,
    CI_ERROR_KIND_CONTINUE_OUTSIDE_OF_LOOP,
    CI_ERROR_KIND_DATA_TYPES_DONT_MATCH,
    CI_ERROR_KIND_DISCARDED_QUALIFIERS_ON_POINTER_CONVERSION,
    CI_ERROR_KIND_DECLARATION_IS_NOT_FOUND,
    CI_ERROR_KIND_DECLARATION_OUTSIDE_OF_VARIABLE_INITIALIZATION,
    CI_ERROR_KIND_DEFAULT_OUTSIDE_OF_SWITCH,
    CI_ERROR_KIND_DIRECT_MEMORY_LEAK,
    CI_ERROR_KIND_DUPLICATE_DEFINE_NAME,
    CI_ERROR_KIND_DUPLICATE_EMBED_PARAMETER,
    CI_ERROR_KIND_DUPLICATE_FIELD,
    CI_ERROR_KIND_DUPLICATE_INPUT,
    CI_ERROR_KIND_DUPLICATE_INPUT_BINARY,
    CI_ERROR_KIND_DUPLICATE_INPUT_HEADER,
    CI_ERROR_KIND_DUPLICATE_INPUT_LIBRARY,
    CI_ERROR_KIND_ELIFDEF_AFTER_ELSE,
    CI_ERROR_KIND_ELIFNDEF_AFTER_ELSE,
    CI_ERROR_KIND_ELIF_AFTER_ELSE,
    CI_ERROR_KIND_ELSE_AFTER_ELSE,
    CI_ERROR_KIND_ENUM_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_ENUM_VARIANT_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_EXCESS_ELEMENTS_IN_SCALAR_INITIALIZER,
    CI_ERROR_KIND_EXCESS_ELEMENTS_IN_STRUCT_OR_UNION_INITIALIZER,
    CI_ERROR_KIND_EXCESS_ELEMENTS_IN_UNION_INITIALIZER,
    CI_ERROR_KIND_EXPECTED_ARRAY_COMPATIBLE_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_ARRAY_INITIALIZATION_EXPRESSION,
    CI_ERROR_KIND_EXPECTED_ARRAY_OR_POINTER,
    CI_ERROR_KIND_EXPECTED_ATTRIBUTE_IDENTIFIER,
    CI_ERROR_KIND_EXPECTED_AT_LEAST_EOF,
    CI_ERROR_KIND_EXPECTED_AT_LEAST_ONE_GENERIC_PARAM,
    CI_ERROR_KIND_EXPECTED_BOOLEAN_COMPATIBLE_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_COMPILE_TIME_EXPRESSION,
    CI_ERROR_KIND_EXPECTED_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_DATA_TYPE_CONTEXT,
    CI_ERROR_KIND_EXPECTED_DECLARATION_DEFINITION,
    CI_ERROR_KIND_EXPECTED_DIGIT,
    CI_ERROR_KIND_EXPECTED_ENDIF,
    CI_ERROR_KIND_EXPECTED_EXPRESSION,
    CI_ERROR_KIND_EXPECTED_EXPRESSION_IN_IF_CONDITION,
    CI_ERROR_KIND_EXPECTED_GENERIC_PARAM,
    CI_ERROR_KIND_EXPECTED_IDENTIFIER,
    CI_ERROR_KIND_EXPECTED_IDENTIFIER_AFTER_DATA_TYPE_CONTEXT,
    CI_ERROR_KIND_EXPECTED_IF_CONDITION,
    CI_ERROR_KIND_EXPECTED_INDEX_CONTEXT_ON_RETURN_VALUE,
    CI_ERROR_KIND_EXPECTED_INTEGER,
    CI_ERROR_KIND_EXPECTED_INTEGER_COMPATIBLE_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_INTEGER_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_INTEGER_FOR_BIT_OPERATION,
    CI_ERROR_KIND_EXPECTED_INTEGER_FOR_LOGICAL_OPERATION,
    CI_ERROR_KIND_EXPECTED_INTEGER_LITERAL_COMPATIBLE_VALUE,
    CI_ERROR_KIND_EXPECTED_INTEGER_OR_FLOAT_FOR_ARITHMETIC_OPERATION,
    CI_ERROR_KIND_EXPECTED_INTEGER_OR_FLOAT_FOR_COMPARISON_OPERATION,
    CI_ERROR_KIND_EXPECTED_KEY,
    CI_ERROR_KIND_EXPECTED_LITERAL_EXPRESSION,
    CI_ERROR_KIND_EXPECTED_MACRO_PARAM_AFTER_STRINGIFY,
    CI_ERROR_KIND_EXPECTED_MAPPING,
    CI_ERROR_KIND_EXPECTED_NAME,
    CI_ERROR_KIND_EXPECTED_NEW_LINE,
    CI_ERROR_KIND_EXPECTED_NON_NULL_EXPRESSION,
    CI_ERROR_KIND_EXPECTED_ONE_OR_MANY_VARIANTS,
    CI_ERROR_KIND_EXPECTED_ONLY_GENERIC_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_ONLY_ONE_EXPRESSION,
    CI_ERROR_KIND_EXPECTED_POINTER_WITH_DEPTH_OF_ONE,
    CI_ERROR_KIND_EXPECTED_POSITIVE_INTEGER_VALUE,
    CI_ERROR_KIND_EXPECTED_RHS_OF_MERGE,
    CI_ERROR_KIND_EXPECTED_SCALAR_VALUE,
    CI_ERROR_KIND_EXPECTED_SEQUENCE_VALUE,
    CI_ERROR_KIND_EXPECTED_STRING_LITERAL,
    CI_ERROR_KIND_EXPECTED_STRING_TOKEN,
    CI_ERROR_KIND_EXPECTED_STRING_VALUE,
    CI_ERROR_KIND_EXPECTED_STRUCT_OR_UNION,
    CI_ERROR_KIND_EXPECTED_STRUCT_OR_UNION_DATA_TYPE,
    CI_ERROR_KIND_EXPECTED_TYPE,
    CI_ERROR_KIND_EXPECTED_VALID_FOR_INIT_CLAUSE,
    CI_ERROR_KIND_EXPECTED_VOID_RETURN_DATA_TYPE,
    CI_ERROR_KIND_EXPRESSION_NOT_RESOLVABLE_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_FAILED_TO_FETCH_BUILTIN_MACROS,
    CI_ERROR_KIND_FAILED_TO_FETCH_DEFAULT_INCLUDE_PATHS,
    CI_ERROR_KIND_FAILED_TO_OPEN_EMBED_PATH,
    CI_ERROR_KIND_FIELD_IS_NOT_FOUND,
    CI_ERROR_KIND_FIELD_NOT_FOUND,
    CI_ERROR_KIND_FLAG_IS_ALREADY_SET,
    CI_ERROR_KIND_FUNCTION_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_GENERIC_PARAMS_ARE_NOT_FOUND,
    CI_ERROR_KIND_GENERIC_PARAMS_COUNT_MISMATCH,
    CI_ERROR_KIND_GENERIC_PARAMS_HOLD_MORE_THAN_ONE_PACK,
    CI_ERROR_KIND_COUNTOF_IS_NOT_WRITTEN_ON_A_PACK,
    CI_ERROR_KIND_PACK_ACCESS_IS_OUT_OF_RANGE,
    CI_ERROR_KIND_UNROLLED_LOOP_HOLDS_NO_COUNTER,
    CI_ERROR_KIND_UNROLLED_LOOP_DOES_NOT_END,
    CI_ERROR_KIND_UNROLLED_LOOP_COUNTER_IS_NOT_STEPPED,
    CI_ERROR_KIND_GENERIC_IS_LEFT_MORE_THAN_ONE_DATA_TYPE,
    CI_ERROR_KIND_GENERIC_PARAMS_ARE_NOT_READ_FROM_THE_CALL,
    CI_ERROR_KIND_GENERIC_ON_A_PACK_STANDS_FOR_MORE_THAN_ONE_DATA_TYPE,
    CI_ERROR_KIND_GENERIC_PARAMS_IN_VARIABLE_CONTEXT,
    CI_ERROR_KIND_GENERIC_PARAMS_NOT_EXPECTED_IN_THIS_CONTEXT,
    CI_ERROR_KIND_GENERIC_PARAM_NAME_NOT_FOUND,
    CI_ERROR_KIND_GENERIC_SELECTION_NO_MATCH,
    CI_ERROR_KIND_GOTO_LABEL_DOES_NOT_EXIST,
    CI_ERROR_KIND_IDENTIFIER_IS_NOT_FOUND,
    CI_ERROR_KIND_INCLUDE_FILE_IS_NOT_FOUND,
    CI_ERROR_KIND_INCOMPATIBLE_DATA_TYPE_CONTEXT,
    CI_ERROR_KIND_INCOMPLETE_ENUM_TYPE,
    CI_ERROR_KIND_INCOMPLETE_STRUCT_TYPE,
    CI_ERROR_KIND_INCOMPLETE_TYPEDEF_TYPE,
    CI_ERROR_KIND_INCOMPLETE_UNION_TYPE,
    CI_ERROR_KIND_INVALID_HAS_FEATURE_ARGUMENT,
    CI_ERROR_KIND_INVALID_VALUE,
    CI_ERROR_KIND_LABEL_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_MACRO_PARAMS_COUNT_MISMATCH,
    CI_ERROR_KIND_MERGE_AT_START,
    CI_ERROR_KIND_NAME_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_NAME_IS_NOT_EXPECTED_HERE,
    CI_ERROR_KIND_NEGATIVE_BIT_FIELD,
    CI_ERROR_KIND_NO_FIELDS,
    CI_ERROR_KIND_OPERATION_EXPECTED_FLOAT_OR_INTEGER,
    CI_ERROR_KIND_OPERATION_EXPECTED_INTEGER,
    CI_ERROR_KIND_OPERATION_EXPECTED_POINTER,
    CI_ERROR_KIND_OPERATION_IS_NOT_POSSIBLE,
    CI_ERROR_KIND_OPERATION_ON_NON_INT_CASTABLE_TYPES,
    CI_ERROR_KIND_PARAMS_COUNT_MISMATCH,
    CI_ERROR_KIND_POST_DECREMENT_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_POST_INCREMENT_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_POTENTIAL_DIRECT_MEMORY_LEAK,
    CI_ERROR_KIND_PREPROCESSOR_IN_MACRO,
    CI_ERROR_KIND_PRE_DECREMENT_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_PRE_INCREMENT_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_READ_OF_DROPPED_IDENTIFIER,
    CI_ERROR_KIND_READ_OF_FREED_IDENTIFIER,
    CI_ERROR_KIND_READ_OF_UNDEFINED_IDENTIFIER,
    CI_ERROR_KIND_SINGLE_LINE_COMMENT_BEFORE_C99,
    CI_ERROR_KIND_SIZEOF_IN_PREPROCESSOR_CONDITION,
    CI_ERROR_KIND_STATIC_ASSERT_FAILED,
    CI_ERROR_KIND_STRINGIFY_OUTSIDE_OF_MACRO,
    CI_ERROR_KIND_STRUCT_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_STRUCT_IS_NOT_FOUND,
    CI_ERROR_KIND_STRUCT_OR_UNION_IS_NOT_FOUND,
    CI_ERROR_KIND_STRUCT_TYPEDEF_OR_UNION_NOT_FOUND,
    CI_ERROR_KIND_TOO_MANY_DOTS_IN_FLOAT_LITERAL,
    CI_ERROR_KIND_TYPEDEF_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_UNEXPECTED_BODY_WITH_TYPEDEF,
    CI_ERROR_KIND_UNEXPECTED_CLOSING_DELIMITER,
    CI_ERROR_KIND_UNEXPECTED_COMMA_AFTER_VARIADIC_PARAM,
    CI_ERROR_KIND_UNEXPECTED_DATA_TYPE_WITH_INITIALIZER,
    CI_ERROR_KIND_UNEXPECTED_ELIF,
    CI_ERROR_KIND_UNEXPECTED_ELIFDEF,
    CI_ERROR_KIND_UNEXPECTED_ELIFNDEF,
    CI_ERROR_KIND_UNEXPECTED_ELSE,
    CI_ERROR_KIND_UNEXPECTED_EOF,
    CI_ERROR_KIND_UNEXPECTED_ERROR_IN_IF_CONDITION,
    CI_ERROR_KIND_UNEXPECTED_EXPRESSION_WITH_TYPEDEF,
    CI_ERROR_KIND_UNEXPECTED_FLOAT_SUFFIX,
    CI_ERROR_KIND_UNEXPECTED_GENERIC_PARAMS,
    CI_ERROR_KIND_UNEXPECTED_INITIALIZER_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_UNEXPECTED_INTEGER_SUFFIX,
    CI_ERROR_KIND_UNEXPECTED_LHS_OF_MERGE,
    CI_ERROR_KIND_UNEXPECTED_OPERATION_ON_STRING,
    CI_ERROR_KIND_UNEXPECTED_PATH_IN_ARRAY_INITIALIZATION,
    CI_ERROR_KIND_UNEXPECTED_PATH_IN_SCALAR_INITIALIZATION,
    CI_ERROR_KIND_UNEXPECTED_RHS_OF_MERGE,
    CI_ERROR_KIND_UNEXPECTED_STRING_AT_PREPROCESSOR_TIME,
    CI_ERROR_KIND_UNEXPECTED_TOKEN,
    CI_ERROR_KIND_UNION_DECLARATION_IS_NOT_FOUND,
    CI_ERROR_KIND_UNION_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_UNKNOWN_FILE_EXTENSION,
    CI_ERROR_KIND_UNKNOWN_STANDARD_ATTRIBUTE,
    CI_ERROR_KIND_UNSURE_OPERATION_AT_COMPILE_TIME,
    CI_ERROR_KIND_VARIABLE_DECLARATION_IN_INIT_CLAUSE_BEFORE_C99,
    CI_ERROR_KIND_VARIABLE_DECLARATION_IN_LABEL,
    CI_ERROR_KIND_VARIABLE_IS_ALREADY_DEFINED,
    CI_ERROR_KIND_VARIABLE_LENGTH_ARRAY_WITH_LINKAGE_OR_STATIC_STORAGE,
    CI_ERROR_KIND_COMPARISON_BETWEEN_DATA_TYPE_AND_VALUE,
    CI_ERROR_KIND_DATA_TYPES_ARE_ONLY_COMPARED_FOR_EQUALITY,
    CI_ERROR_KIND_VA_ARGS_IN_NON_VARIADIC_MACRO,
    CI_ERROR_KIND_AMBIGUOUS_METHOD_RECEIVER,
    CI_ERROR_KIND_METHOD_IS_NOT_FOUND,
    CI_ERROR_KIND_METHOD_IS_SHADOWED_BY_MEMBER,
    CI_ERROR_KIND_METHOD_RECEIVER_DOES_NOT_FIT
};

typedef struct CIError
{
    enum CIErrorKind kind;
    union
    {
        char *preprocessor_error; // char* (&)
        char *expected_token;     // char* (&)
        // The message the assertion was declared with, or NULL when it was
        // declared without one.
        char *static_assert_failed; // char*? (&)
    };
} CIError;

/**
 *
 * @brief Construct CIError type.
 */
inline CONSTRUCTOR(CIError, CIError, enum CIErrorKind kind)
{
    return (CIError){ .kind = kind };
}

/**
 *
 * @brief Construct CIError type (CI_ERROR_KIND_PREPROCESSOR_ERROR).
 */
inline VARIANT_CONSTRUCTOR(CIError,
                           CIError,
                           preprocessor_error,
                           char *preprocessor_error)
{
    return (CIError){ .kind = CI_ERROR_KIND_PREPROCESSOR_ERROR,
                      .preprocessor_error = preprocessor_error };
}

/**
 *
 * @brief Construct CIError type (CI_ERROR_KIND_EXPECTED_TOKEN).
 * @param expected_token The spelling of what was expected, e.g. "`;`". It is
 * borrowed and must outlive the diagnostic.
 */
inline VARIANT_CONSTRUCTOR(CIError,
                           CIError,
                           expected_token,
                           char *expected_token)
{
    return (CIError){ .kind = CI_ERROR_KIND_EXPECTED_TOKEN,
                      .expected_token = expected_token };
}

/**
 *
 * @brief Construct CIError type (CI_ERROR_KIND_STATIC_ASSERT_FAILED).
 * @param static_assert_failed char*? - The message the assertion was declared
 * with, NULL when it was declared without one. It is borrowed and must outlive
 * the diagnostic.
 */
inline VARIANT_CONSTRUCTOR(CIError,
                           CIError,
                           static_assert_failed,
                           char *static_assert_failed)
{
    return (CIError){ .kind = CI_ERROR_KIND_STATIC_ASSERT_FAILED,
                      .static_assert_failed = static_assert_failed };
}

/**
 *
 * @brief Convert CIError in msg.
 */
char *
to_msg__CIError(const CIError *self);

/**
 *
 * @brief Convert CIError in code.
 */
char *
to_code__CIError(const CIError *self);

/**
 *
 * @brief Convert CIError in str.
 */
char *
to_string__CIError(const CIError *self);

#endif // LILY_CORE_CC_CI_DIAGNOSTIC_ERROR_H
