#!/usr/bin/env bash

if [[ ! -d "build/Debug" ]]
then
	echo 'Skipping pre-commit. Expected to have `build/Debug`. Please configure the project by running `make debug`.'
	exit 0
fi

# Check build
cd patches && patch -r ../include/base/macros.h disable_debug.patch > /dev/null
cd ..
patch_status=$?

ninja -C build/Debug

# Format all files
make format

# Run tests
ninja test -C build/Debug

# Revert to patch modification
if [ $patch_status -eq 0 ]
then
	cd patches && patch -r ../include/base/macros.h enable_debug.patch > /dev/null
	cd ..
fi
