#!/bin/sh

# Check build
cd patches && patch -r ../include/base/macros.h disable_debug.patch > /dev/null
cd ..
patch_status=$?

ninja -C build/Debug

# Format all files 
make format

# Run all samples
# NOTE: If you can't run `./scripts/test_samples.sh`, replace with `./scripts/test_samples.py`.
./scripts/test_samples.sh

# Revert to patch modification
if [ $patch_status -eq 0 ]
then
	cd patches && patch -r ../include/base/macros.h enable_debug.patch > /dev/null
	cd ..
fi
