/*
 * MIT License
 *
 * Copyright (c) 2022-2023 ArthurPV
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef LILY_CORE_LILY_ERROR_H
#define LILY_CORE_LILY_ERROR_H

#include <base/macros.h>

enum LilyErrorKind
{
    LILY_ERROR_KIND_UNEXPECTED_TOKEN,
    LILY_ERROR_KIND_UNCLOSED_CHAR_LITERAL,
    LILY_ERROR_KIND_INVALID_ESCAPE,
    LILY_ERROR_KIND_UNCLOSED_COMMENT_BLOCK,
    LILY_ERROR_KIND_INVALID_CHAR_LITERAL,
    LILY_ERROR_KIND_UNCLOSED_STRING_LITERAL,
    LILY_ERROR_KIND_INT8_OUT_OF_RANGE,
    LILY_ERROR_KIND_INT16_OUT_OF_RANGE,
    LILY_ERROR_KIND_INT32_OUT_OF_RANGE,
    LILY_ERROR_KIND_INT64_OUT_OF_RANGE,
    LILY_ERROR_KIND_UINT8_OUT_OF_RANGE,
    LILY_ERROR_KIND_UINT16_OUT_OF_RANGE,
    LILY_ERROR_KIND_UINT32_OUT_OF_RANGE,
    LILY_ERROR_KIND_UINT64_OUT_OF_RANGE,
    LILY_ERROR_KIND_ISIZE_OUT_OF_RANGE,
    LILY_ERROR_KIND_USIZE_OUT_OF_RANGE,
    LILY_ERROR_KIND_INVALID_LITERAL_SUFFIX,
    LILY_ERROR_KIND_INVALID_HEXADECIMAL_LITERAL,
    LILY_ERROR_KIND_INVALID_OCTAL_LITERAL,
    LILY_ERROR_KIND_INVALID_BIN_LITERAL,
    LILY_ERROR_KIND_INVALID_FLOAT_LITERAL,
    LILY_ERROR_KIND_MISMATCHED_CLOSING_DELIMITER,
    LILY_ERROR_KIND_UNEXPECTED_CHARACTER,
    LILY_ERROR_KIND_EXPECTED_IMPORT_VALUE,
    LILY_ERROR_KIND_EXPECTED_IDENTIFIER,
    LILY_ERROR_KIND_DUPLICATE_PACKAGE_DECLARATION,
    LILY_ERROR_KIND_PACKAGE_NAME_ALREADY_DEFINED,
    LILY_ERROR_KIND_BAD_IMPORT_VALUE,
    LILY_ERROR_KIND_UNKNOWN_IMPORT_AT_FLAG,
    LILY_ERROR_KIND_UNEXPECTED_CHARACTER_IN_IMPORT_VALUE,
    LILY_ERROR_KIND_NAME_CONFLICT,
    LILY_ERROR_KIND_EOF_NOT_EXPECTED,
    LILY_ERROR_KIND_EXPECTED_MODULE_IDENTIFIER,
    LILY_ERROR_KIND_EXPECTED_FUN_IDENTIFIER,
    LILY_ERROR_KIND_EXPECTED_TOKEN,
    LILY_ERROR_KIND_UNEXPECTED_TOKEN_IN_FUNCTION_BODY,
    LILY_ERROR_KIND_BAD_KIND_OF_TYPE,
    LILY_ERROR_KIND_IMPL_IS_ALREADY_DEFINED,
    LILY_ERROR_KIND_INHERIT_IS_ALREADY_DEFINED,
    LILY_ERROR_KIND_BAD_KIND_OF_OBJECT,
    LILY_ERROR_KIND_INHERIT_IS_NOT_EXPECTED,
    LILY_ERROR_KIND_IMPL_IS_NOT_EXPECTED,
    LILY_ERROR_KIND_EXPECTED_DATA_TYPE,
    LILY_ERROR_KIND_SET_IS_DUPLICATE,
    LILY_ERROR_KIND_GET_IS_DUPLICATE,
    LILY_ERROR_KIND_EXPECTED_EXPRESSION,
    LILY_ERROR_KIND_MISS_ONE_OR_MANY_EXPRESSIONS,
    LILY_ERROR_KIND_MISS_ONE_OR_MANY_IDENTIFIERS,
    LILY_ERROR_KIND_EXPECTED_ONE_OR_MANY_CHARACTERS,
    LILY_ERROR_KIND_FEATURE_NOT_YET_SUPPORTED,
    LILY_ERROR_KIND_EXPECTED_ASM_PARAM,
    LILY_ERROR_KIND_EXPECTED_COMPTIME_STRING_LITERAL,
    LILY_ERROR_KIND_EXPECTED_ONLY_ONE_EXPRESSION,
    LILY_ERROR_KIND_VARIABLE_DECLARATION_IS_NOT_EXPECTED,
    LILY_ERROR_KIND_EXPECTED_ONLY_ONE_PATTERN,
    LILY_ERROR_KIND_EXPECTED_ONLY_ONE_DATA_TYPE
};

typedef struct LilyError
{
    enum LilyErrorKind kind;
    union
    {
        char *unexpected_token;
    };
} LilyError;

/**
 *
 * @brief Construct LilyError.
 */
inline CONSTRUCTOR(LilyError, LilyError, enum LilyErrorKind kind)
{
    return (LilyError){ .kind = kind };
}

/**
 *
 * @brief Construct LilyError (LILY_ERROR_KIND_UNEXPECTED_TOKEN).
 */
inline VARIANT_CONSTRUCTOR(LilyError,
                           LilyError,
                           unexpected_token,
                           char *unexpected_token)
{
    return (LilyError){ .kind = LILY_ERROR_KIND_UNEXPECTED_TOKEN,
                        .unexpected_token = unexpected_token };
}

/**
 *
 * @brief Convert LilyError in msg.
 */
char *
to_msg__LilyError(const LilyError *self);

/**
 *
 * @brief Convert LilyError in code.
 */
char *
to_code__LilyError(const LilyError *self);

/**
 *
 * @brief Convert LilyError in str.
 */
char *
to_string__LilyError(const LilyError *self);

#endif // LILY_CORE_LILY_ERROR_H
