#ifndef LILY_CORE_LILY_VISIBILITY_H
#define LILY_CORE_LILY_VISIBILITY_H

enum LilyVisibility
{
    LILY_VISIBILITY_PUBLIC,
    LILY_VISIBILITY_PRIVATE,
    LILY_VISIBILITY_STATIC
};

#endif // LILY_CORE_LILY_VISIBILITY_H